### ISSUE TITLE
Python 3 compatibility - bitfield

### ISSUE THREAD

**Issue by martinohanlon** [adafruit/Adafruit_AMG88xx_python#2]
There is an error when using this library with Python 3

```
Traceback (most recent call last):
  File "examples/pixels_test.py", line 40, in <module>
    sensor = Adafruit_AMG88xx()
  File "/usr/local/lib/python3.5/dist-packages/Adafruit_AMG88xx/Adafruit_AMG88xx.py", line 91, in __init__
    self._pctl = Adafruit_bitfield([('PCTL', 8)])
  File "/usr/local/lib/python3.5/dist-packages/Adafruit_bitfield/Adafruit_bitfield.py", line 8, in __init__
    for key, value in self._structure.iteritems():
AttributeError: 'collections.OrderedDict' object has no attribute 'iteritems'
```

The error originates from Adafruit-bitfield. I was going to fix and provide a PR but I cant find the repo - pypi points to [https://github.com/adafruit/Adafruit_bitfield_python](https://github.com/adafruit/Adafruit_bitfield_python) but it doesn't exist.

**Comment by deanm1278** [comment]
@martinohanlon oops the repo was set to private. https://github.com/adafruit/Adafruit_bitfield_python is now public.
Looks like iteritems was removed in python 3, feel free to fix and PR if you'd like! otherwise I will fix soon.
Thanks!

**Comment by martinohanlon** [comment]
PR submitted [https://github.com/adafruit/Adafruit_bitfield_python/pull/1](https://github.com/adafruit/Adafruit_bitfield_python/pull/1).

You will also have to modify [setup.py](https://github.com/adafruit/Adafruit_AMG88xx_python/blob/master/setup.py#L29) to state the new version is required when its available on pypi. :)

**Comment by deanm1278** [comment]
ok @martinohanlon all merged and verified working, thanks!

**Comment by martinohanlon** [comment]
:+1:
