### ISSUE TITLE
temp calc for negative numbers not correct

### ISSUE THREAD

**Issue by kw123** [adafruit/Adafruit_AMG88xx_python#4]
the calculation for the pixel values is not correct.
the adafruit spec sheet from panasonic states: https://cdn-learn.adafruit.com/assets/assets/000/043/261/original/Grid-EYE_SPECIFICATIONS%28Reference%29.pdf?1498680225
on page 14

""(11) Temperature Register
Register for reading only to indicate temperature data per 1 pixel.
Temperature Data of each pixel is 12 bit data and 2 byte data.
1 LSB has 12 bit resolution (11 bit + sign) which is equivalent to 0.25℃
and it is indicated as **two's complement** form.""

the correct conversion should be:

 ```
def twoCompl12(self, val):
        if  0x7FF & val == val:
            return float(val)
        else:
            return float(val-4096 )
```

for the thermistor it is correct
 ```
def signedMag12ToFloat(self, val):
        #take first 11 bits as absolute val
        if  0x7FF & val == val:
            return float(val)
        else:
            return  - float(0x7FF & val)
```

Panasonic has apparently used 2 different forms to do negative numbers for the thermistor and the pixels.

This was tested with ice and in the freezer: the new formula seems to show the proper numbers, using the posted python formulas one gets wrong numbers for negative C surfaces

Karl

**Comment by deanm1278** [comment]
fixed! thank you!
https://github.com/adafruit/Adafruit_AMG88xx_python/commit/847541b5e5d3592ebb7ceaca7ce2e8cf51dff313
