### ISSUE TITLE
HDMI output example

### ISSUE THREAD

**Issue by yratof** [adafruit/Adafruit_AMG88xx_python#5]
Is it possible to show an example of running the thermal cam via HDMI. Currently, I've commented out the `os.putenv` line, expecting it to work, but the screen goes black and nothing is drawn.

Perhaps i'm missing something?

**Comment by yratof** [comment]
Investigating further, there's a limit to the screen size that this script will output — if we force the Framebuffer to be a 4th of the resolution, it can be forced to display

**Comment by jackjt8** [comment]
@yratof I'm getting the same issue when trying to run the script on a 320x240 composite display (framebuffer to match). What framebuffer size did you use?

**Comment by isabellachow** [comment]
@yratof @jackjt8  i'm trying to force hdmi monitor display for art installation! if y'all have any advice, would be greatly appreciated.

**Comment by yratof** [comment]
@jackjt8 I've been using a square resolution, just so it doesn't stretch and it outputs fine. 

@isabellachow What solved the HDMI out issue for me was simply removing this line:

`os.putenv('SDL_FBDEV', '/dev/fb1')`

Without it, it defaults to whatever screen is available is seems

**Comment by isabellachow** [comment]
thankyou! worked a treat.

is there a way to make it stretch across display, even if it distorts?

**Comment by yratof** [comment]
@isabellachow I think you could play around with this part:

```
  displayPixelWidth = width / 30
  displayPixelHeight = height / 30
```

**Comment by jackjt8** [comment]
@yratof What framebuffer are you referring to? I haven't modified any of the code with the exception of commenting out the `os.env` line. The framebuffer in question would be the one you have set in `/boot/config.txt` or it might be tied to the monitor resolution. From what I was able to gather, it seems Pygame doesn't support framebuffers below 640x480 and base upon your first two comments it does seem that Pygame has an upper limit; I can't test it right now, but... if you can provide at least that resolution it'll be a big help.

@yratof @isabellachow That would only alter the `displayPixels`. I would recommend that you change the `width` and `height` first as that'll affect both the `displayPixelss` and `pygame.display.set_mode()`. When the `lcd.fill()` occurs, ie the solid colour after starting the script, you should be able to see the area that `pygame.display.set_mode` can draw to. Removing the `/ 30` will then let to get a 1:1 between the `displayPixels` and the screens width/height, ie as much screen fill as `lcd.fill()` shows. If you using a width/height of 1280x720 (or equivalent 16 by 9) and you want a square draw, you can use `displayPixelWidth = width / (16/9)`.

Pygame won't have an issue with doing this, can't say the same about Adafruit's examples.

**Comment by yratof** [comment]
I'm running at 320x240 on my handheld Thermal cam now – @jackjt8 I would try to run this easy installer if you've got a similar screen: https://learn.adafruit.com/adafruit-2-2-pitft-hat-320-240-primary-display-for-raspberry-pi/easy-install

**Comment by jackjt8** [comment]
As I said In my original post, I'm running a 320x240 composite display (with a 640x480 config.txt framebuffer per my previous reply).

**Comment by isabellachow** [comment]
hmm i gave it a go - if i simply change width/height, it gave me 'segmentation error'. if i also changed displaypixels, then i got 'no video mode large enough'

**Comment by ladyada** [comment]
hiya we're archiving this repo because we've moved to only using the circuitpython version of this library. it works great on raspi & the example code has been adapted as well! 
https://github.com/adafruit/Adafruit_CircuitPython_AMG88xx

to keep this repo from getting used now that its deprecated, we'll be closing all issues and archiving. please feel free to open a new issue at https://github.com/adafruit/Adafruit_CircuitPython_AMG88xx - any pull req's will also be welcome there

thanks!!
