### ISSUE TITLE
Calculation for the positive pixel values is not correct.

### ISSUE THREAD

**Issue by SaraCamara** [adafruit/Adafruit_AMG88xx_python#7]
Please, my sensor has values between 20º and 25º when the temperatures are actually lower or higher than those shown. Can anyone help me explain how to calibrate the temperature values shown for real?
I'm a nooby in python and I have not found a satisfactory material on how we can do this.
Tks!

**Comment by caternuson** [comment]
In general, you would need to use a blackbody calibrator. Please post the issues you are having with your specific case in the forums: 
https://forums.adafruit.com/viewforum.php?f=19
We can do technical troubleshooting there first. If it seems like an issue with the driver, then we can open an issue here.
